# Generated by Django 4.2.16 on 2025-03-19 10:47

from django.db import migrations, models
import utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, storage=utils.helpers.AzureMediaStorage(), upload_to='competition_banners/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, storage=utils.helpers.AzureMediaStorage(), upload_to='tournament_banners/'),
        ),
    ]
